export const villes = [
    { value: 'Casablanca', label: 'Casablanca' },
    { value: 'Fes', label: 'Fès' },
    { value: 'Marrakech', label: 'Marrakech' },
    { value: 'Tangier', label: 'Tanger' },
    { value: 'Sale', label: 'Salé' },
    { value: 'Rabat', label: 'Rabat' },
    { value: 'Meknes', label: 'Meknès' },
    { value: 'OujdaAngad', label: 'Oujda-Angad' },
    { value: 'Kenitra', label: 'Kénitra' },
    { value: 'Agadir', label: 'Agadir' },
    { value: 'Tetouan', label: 'Tétouan' },
    { value: 'Taourirt', label: 'Taourirt' },
    { value: 'Temara', label: 'Témara' },
    { value: 'Safi', label: 'Safi' },
    { value: 'Khenifra', label: 'Khénifra' },
    { value: 'ElJadida', label: 'El Jadida' },
    { value: 'Laayoune', label: 'Laâyoune' },
    { value: 'Mohammedia', label: 'Mohammedia' },
    { value: 'Khouribga', label: 'Khouribga' },
    { value: 'BeniMellal', label: 'Béni Mellal' },
    { value: 'AitMelloul', label: 'Ait Melloul' },
    { value: 'Nador', label: 'Nador' },
    { value: 'Taza', label: 'Taza' },
    { value: 'Settat', label: 'Settat' },
    { value: 'Barrechid', label: 'Barrechid' },
    { value: 'AlKhmissat', label: 'Al Khmissat' },
    { value: 'Inezgane', label: 'Inezgane' },
    { value: 'KsarElKebir', label: 'Ksar El Kebir' },
    { value: 'MyDrarga', label: 'My Drarga' },
    { value: 'Larache', label: 'Larache' },
    { value: 'Guelmim', label: 'Guelmim' },
    { value: 'Berkane', label: 'Berkane' },
    { value: 'AdDakhla', label: 'Ad Dakhla' },
    { value: 'Bouskoura', label: 'Bouskoura' },
    { value: 'AlFqihBenSalah', label: 'Al Fqih Ben Çalah' },
    { value: 'OuedZem', label: 'Oued Zem' },
    { value: 'SidiSlimane', label: 'Sidi Slimane' },
    { value: 'Errachidia', label: 'Errachidia' },
    { value: 'Guercif', label: 'Guercif' },
    { value: 'OuladTeima', label: 'Oulad Teïma' },
    { value: 'BenGuerir', label: 'Ben Guerir' },
    { value: 'Sefrou', label: 'Sefrou' },
    { value: 'Fnidq', label: 'Fnidq' },
    { value: 'SidiQacem', label: 'Sidi Qacem' },
    { value: 'Tiznit', label: 'Tiznit' },
    { value: 'MoulayAbdallah', label: 'Moulay Abdallah' },
    { value: 'Youssoufia', label: 'Youssoufia' },
    { value: 'Martil', label: 'Martil' },
    { value: 'AinHarrouda', label: 'Aïn Harrouda' },
    { value: 'SouqSebt', label: 'Souq Sebt Oulad Nemma' },
    { value: 'Skhirate', label: 'Skhirate' },
    { value: 'Ouezzane', label: 'Ouezzane' },
    { value: 'SidiYahyaZaer', label: 'Sidi Yahya Zaer' },
    { value: 'AlHoceima', label: 'Al Hoceïma' },
    { value: 'Mdiq', label: 'M’diq' },
    { value: 'Midalt', label: 'Midalt' },
    { value: 'Azrou', label: 'Azrou' },
    { value: 'ElKelaaSrarhna', label: 'El Kelaa des Srarhna' },
    { value: 'AinElAouda', label: 'Ain El Aouda' },
    { value: 'BeniYakhlef', label: 'Beni Yakhlef' },
    { value: 'AdDarwa', label: 'Ad Darwa' },
    { value: 'AlAaroui', label: 'Al Aaroui' },
    { value: 'QasbatTadla', label: 'Qasbat Tadla' },
    { value: 'Boujad', label: 'Boujad' },
    { value: 'Jerada', label: 'Jerada' },
    { value: 'Mrirt', label: 'Mrirt' },
    { value: 'ElAioun', label: 'El Aïoun' },
    { value: 'Azemmour', label: 'Azemmour' },
    { value: 'Temsia', label: 'Temsia' },
    { value: 'Zagora', label: 'Zagora' },
    { value: 'AitOurir', label: 'Ait Ourir' },
    { value: 'Azilal', label: 'Azilal' },
    { value: 'SidiYahiaElGharb', label: 'Sidi Yahia El Gharb' },
    { value: 'Biougra', label: 'Biougra' },
    { value: 'Zaio', label: 'Zaïo' },
    { value: 'Aguelmous', label: 'Aguelmous' },
    { value: 'ElHajeb', label: 'El Hajeb' },
    { value: 'Zeghanghane', label: 'Zeghanghane' },
    { value: 'Imzouren', label: 'Imzouren' },
    { value: 'TitMellil', label: 'Tit Mellil' },
    { value: 'MechraaBelKsiri', label: 'Mechraa Bel Ksiri' },
    { value: 'AlAttawia', label: 'Al ’Attawia' },
    { value: 'Demnat', label: 'Demnat' },
    { value: 'Arfoud', label: 'Arfoud' },
    { value: 'Tameslouht', label: 'Tameslouht' },
    { value: 'BouArfa', label: 'Bou Arfa' },
    { value: 'SidiSmail', label: 'Sidi Smai’il' },
    { value: 'SoukJorf', label: 'Souk et Tnine Jorf el' },
    { value: 'Mehdya', label: 'Mehdya' },
    { value: 'AinTaoujdat', label: 'Aïn Taoujdat' },
    { value: 'Chichaoua', label: 'Chichaoua' },
    { value: 'Tahla', label: 'Tahla' },
    { value: 'OuladYaich', label: 'Oulad Yaïch' },
    { value: 'MoulayBousselham', label: 'Moulay Bousselham' },
    { value: 'Iheddadene', label: 'Iheddadene' },
    { value: 'Missour', label: 'Missour' },
    { value: 'ZawyatCheikh', label: 'Zawyat ech Cheïkh' },
    { value: 'Bouknadel', label: 'Bouknadel' },
    { value: 'OuladTayeb', label: 'Oulad Tayeb' },
    { value: 'OuladBarhil', label: 'Oulad Barhil' },
    { value: 'BirJdid', label: 'Bir Jdid' },
    { value: 'Tifariti', label: 'Tifariti' }
  ];
  